#!/usr/bin/env python3
"""
report.py - Generate learner tracker report

Reads memory files and generates/updates the tracker.
Uses Python stdlib only - no external dependencies.

Usage:
    python .claude/path-engine/report.py

Output:
    Writes/updates paths/Beginner/tracker.md
"""

import json
from datetime import datetime
from pathlib import Path
from typing import Optional


# Configuration
REPO_ROOT = Path(__file__).parent.parent.parent
MEMORY_DIR = REPO_ROOT / ".claude" / "memory"
LEARNER_LEVEL = "Beginner"
PATHS_DIR = REPO_ROOT / "paths" / LEARNER_LEVEL


def load_json(path: Path) -> dict:
    """Load a JSON file."""
    if not path.exists():
        return {}
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def load_jsonl(path: Path) -> list:
    """Load a JSONL file."""
    if not path.exists():
        return []
    entries = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                entries.append(json.loads(line))
    return entries


def get_latest_evaluation(progress: list) -> Optional[dict]:
    """Get the most recent evaluation event."""
    evaluations = [e for e in progress if e.get("event") == "evaluation"]
    if not evaluations:
        return None
    return evaluations[-1]


def count_events(progress: list, event_type: str) -> int:
    """Count events of a specific type."""
    return len([e for e in progress if e.get("event") == event_type])


def get_recent_decisions(decisions: list, n: int = 5) -> list:
    """Get the N most recent decisions."""
    return decisions[-n:] if decisions else []


def generate_report(profile: dict, progress: list, decisions: list) -> str:
    """Generate the tracker report."""
    now = datetime.utcnow().isoformat() + "Z"
    level = profile.get("level", LEARNER_LEVEL)
    current_month = profile.get("current_month", 1)
    current_week = profile.get("current_week", 1)
    started = profile.get("started", "Unknown")

    # Get stats
    evaluation = get_latest_evaluation(progress)
    tasks_completed = count_events(progress, "task_completed")
    mvps_shipped = count_events(progress, "mvp_shipped")
    weeks_completed = count_events(progress, "week_end")

    # Build report
    report = f"""# Progress Tracker

**Level**: {level}
**Started**: {started}
**Last Updated**: {now}

---

## Current Position

- **Month**: {current_month} of 12
- **Week**: {current_week} of 4

## Overall Progress

| Metric | Value |
|--------|-------|
| Tasks Completed | {tasks_completed} |
| MVPs Shipped | {mvps_shipped} |
| Weeks Completed | {weeks_completed} |

"""

    # Add evaluation section if available
    if evaluation:
        score = evaluation.get("overall_score", 0)
        categories = evaluation.get("categories", {})

        # Score bar
        bar = "█" * (score // 10) + "░" * (10 - score // 10)

        report += f"""## Latest Evaluation

**Score**: {score}/100 [{bar}]
**Date**: {evaluation.get('timestamp', 'Unknown')}

### Category Breakdown

| Category | Score |
|----------|-------|
"""
        for cat, cat_score in categories.items():
            cat_bar = "█" * (cat_score // 10) + "░" * (10 - cat_score // 10)
            report += f"| {cat.title()} | {cat_score} [{cat_bar}] |\n"

        # Add recommendations
        recommendations = evaluation.get("recommendations", [])
        if recommendations:
            report += "\n### Recommendations\n\n"
            for rec in recommendations:
                report += f"- {rec}\n"

        report += "\n"

    # Add recent decisions
    recent_decisions = get_recent_decisions(decisions)
    if recent_decisions:
        report += """## Recent Decisions

| Date | Decision | Details |
|------|----------|---------|
"""
        for dec in recent_decisions:
            ts = dec.get("timestamp", "")[:10]
            decision_type = dec.get("decision", "unknown")
            rationale = dec.get("rationale", "")[:50]
            report += f"| {ts} | {decision_type} | {rationale}... |\n"

        report += "\n"

    # Add quick links
    report += """## Quick Links

- [Dashboard](README.md)
- [Current Month](month-{:02d}/README.md)
- [Journal](journal/README.md)
- [Commands](../../docs/commands.md)
- [Best Practices](../../.claude/memory/best_practices.md)

---

## Next Steps

1. Run `/status` to see current state
2. Run `/plan-week` to plan your week
3. Work on your tasks
4. Run `/evaluate` to check progress
5. Run `/report` to update this tracker

---

*This file is auto-generated by `report.py`. Do not edit manually.*
*Memory files (`.claude/memory/*`) are the source of truth.*
""".format(current_month)

    return report


def main():
    """Generate and write the report."""
    print("=" * 50)
    print("  AI Practitioner Learning OS - Report")
    print("=" * 50)
    print()

    # Load data
    profile = load_json(MEMORY_DIR / "learner_profile.json")
    progress = load_jsonl(MEMORY_DIR / "progress_log.jsonl")
    decisions = load_jsonl(MEMORY_DIR / "decisions.jsonl")

    # Generate report
    report = generate_report(profile, progress, decisions)

    # Ensure paths directory exists
    PATHS_DIR.mkdir(parents=True, exist_ok=True)

    # Write report
    tracker_path = PATHS_DIR / "tracker.md"
    with open(tracker_path, "w", encoding="utf-8") as f:
        f.write(report)

    print(f"Report written to: {tracker_path}")
    print()

    # Print summary
    evaluation = get_latest_evaluation(progress)
    if evaluation:
        print(f"Current Score: {evaluation.get('overall_score', 'N/A')}/100")
    print(f"Tasks Completed: {count_events(progress, 'task_completed')}")
    print(f"MVPs Shipped: {count_events(progress, 'mvp_shipped')}")
    print()

    print("=" * 50)


if __name__ == "__main__":
    main()
