#!/usr/bin/env python3
"""
Report Generator for AI Practitioner Learning OS.

Generates and updates the learner tracker.

Usage:
    python report.py [--dry-run] [--json]

Output:
    Updated tracker.md (or preview in dry-run mode)
"""

import argparse
import json
from datetime import datetime
from pathlib import Path
from typing import Any


# Paths
REPO_ROOT = Path(__file__).parent.parent.parent
MEMORY_DIR = REPO_ROOT / ".claude" / "memory"
PATHS_DIR = REPO_ROOT / "paths" / "advanced"
TRACKER_PATH = PATHS_DIR / "tracker.md"

# Import from evaluate
from evaluate import compute_scores, load_json, load_jsonl, count_dod_items, PASSING_THRESHOLD


def generate_month_summary(month: int, scores: dict) -> str:
    """Generate summary for a month."""
    status_emoji = "✅" if scores["overall"] >= PASSING_THRESHOLD else "⚠️"
    completed, total = count_dod_items(month)

    return f"""### Month {month:02d}

- **Status**: {status_emoji} {scores['overall']:.1f}%
- **Completion**: {completed}/{total} DoD items
- **Quality**: {scores['quality']:.1f}%
- **Velocity**: {scores['velocity']:.1f}%
"""


def get_recent_activity(limit: int = 10) -> list[dict]:
    """Get recent activity from progress log."""
    progress_log = load_jsonl(MEMORY_DIR / "progress_log.jsonl")
    return progress_log[-limit:]


def get_recent_decisions(limit: int = 5) -> list[dict]:
    """Get recent decisions."""
    decisions = load_jsonl(MEMORY_DIR / "decisions.jsonl")
    return decisions[-limit:]


def generate_tracker(dry_run: bool = False) -> str:
    """Generate the tracker document."""
    profile = load_json(MEMORY_DIR / "learner_profile.json")
    current_month = profile.get("current_month", 1)
    level = profile.get("level", "advanced")
    started = profile.get("started", "Unknown")

    # Compute current scores
    scores = compute_scores(current_month)
    status = "On Track" if scores["overall"] >= PASSING_THRESHOLD else "Needs Attention"

    # Recent activity
    recent_activity = get_recent_activity()
    recent_decisions = get_recent_decisions()

    tracker = f"""# Learning Tracker

**Level**: {level.title()}
**Started**: {started}
**Current Month**: {current_month:02d}
**Last Updated**: {datetime.now().strftime("%Y-%m-%d %H:%M")}

---

## Current Status

| Metric | Value |
|--------|-------|
| Overall Progress | {scores['overall']:.1f}% |
| Status | {status} |
| Threshold | {PASSING_THRESHOLD}% |

### Score Breakdown

| Category | Score | Status |
|----------|-------|--------|
| Completion | {scores['completion']:.1f}% | {"✅" if scores['completion'] >= 70 else "⚠️"} |
| Quality | {scores['quality']:.1f}% | {"✅" if scores['quality'] >= 70 else "⚠️"} |
| Velocity | {scores['velocity']:.1f}% | {"✅" if scores['velocity'] >= 70 else "⚠️"} |
| Reflection | {scores['reflection']:.1f}% | {"✅" if scores['reflection'] >= 70 else "⚠️"} |

---

## Month Progress

"""

    # Add current month summary
    tracker += generate_month_summary(current_month, scores)

    # Add progress for previous months
    for m in range(1, current_month):
        prev_scores = compute_scores(m)
        tracker += f"""
### Month {m:02d}
- **Status**: ✅ Completed ({prev_scores['overall']:.1f}%)
"""

    # Upcoming months
    tracker += """
---

## Upcoming Months

"""
    for m in range(current_month + 1, min(current_month + 4, 13)):
        tracker += f"- Month {m:02d}: Pending\n"

    # Recent activity
    tracker += """
---

## Recent Activity

| Date | Type | Description |
|------|------|-------------|
"""
    for activity in reversed(recent_activity):
        ts = activity.get("timestamp", "")[:10]
        atype = activity.get("type", "unknown")
        desc = activity.get("message", activity.get("description", activity.get("task", "-")))
        if len(desc) > 50:
            desc = desc[:47] + "..."
        tracker += f"| {ts} | {atype} | {desc} |\n"

    # Recent decisions
    tracker += """
---

## Recent Decisions

"""
    for decision in reversed(recent_decisions):
        ts = decision.get("timestamp", "")[:10]
        desc = decision.get("decision", "Unknown decision")
        tracker += f"- **{ts}**: {desc}\n"

    # Quick actions
    tracker += """
---

## Quick Actions

```bash
# Check status
/status

# Plan the week
/plan-week

# Evaluate progress
python .claude/path-engine/evaluate.py

# Get adaptation proposals
python .claude/path-engine/adapt.py

# Update this tracker
python .claude/path-engine/report.py
```

---

## Notes

_This tracker is regenerated by `report.py`. Memory files (`.claude/memory/`) are the source of truth._

"""

    return tracker


def main():
    parser = argparse.ArgumentParser(description="Generate learner tracker")
    parser.add_argument("--dry-run", action="store_true", help="Preview without writing")
    parser.add_argument("--json", action="store_true", help="Output as JSON")
    args = parser.parse_args()

    if args.json:
        profile = load_json(MEMORY_DIR / "learner_profile.json")
        current_month = profile.get("current_month", 1)
        scores = compute_scores(current_month)

        output = json.dumps({
            "profile": profile,
            "current_month": current_month,
            "scores": scores,
            "recent_activity": get_recent_activity(),
            "recent_decisions": get_recent_decisions(),
            "timestamp": datetime.now().isoformat(),
        }, indent=2)
        print(output)
        return

    tracker_content = generate_tracker(dry_run=args.dry_run)

    if args.dry_run:
        print("=== DRY RUN: Tracker Preview ===\n")
        print(tracker_content)
        print("\n=== End Preview ===")
        print(f"\nTo write: python report.py (without --dry-run)")
    else:
        # Ensure directory exists
        TRACKER_PATH.parent.mkdir(parents=True, exist_ok=True)

        # Write tracker
        TRACKER_PATH.write_text(tracker_content)
        print(f"✅ Tracker updated: {TRACKER_PATH}")
        print(f"   Last updated: {datetime.now().strftime('%Y-%m-%d %H:%M')}")


if __name__ == "__main__":
    main()
